[package]
name = "blimp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
common = { path = "../common" }
tokio = { version = "1.40.0", features = ["macros", "rt", "rt-multi-thread"] }

[features]
default = []
network = ["common/network"]
