[package]
name = "blimp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-web = "4.5.1"
common = { path = "../common" }
env_logger = "0.11.3"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
