[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.87"
bytes = "1.7.1"
bzip2 = "0.4.4"
flate2 = "1.0.33"
futures = "0.3.30"
futures-util = "0.3.30"
infer = "0.16.0"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["blocking", "json", "stream"], optional = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tar = "0.4.41"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread"] }
xz2 = "0.1.7"

[features]
default = []
network = ["dep:reqwest"]
