[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1.2.1"
flate2 = "1.0.22"
futures = "0.3.19"
futures-util = "0.3.21"
reqwest = { version = "0.11", features = ["blocking", "json", "stream"], optional = true }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
tar = "0.4.38"
tokio = { version = "1.21.2", features = ["rt", "rt-multi-thread"] }
xz2 = "0.1.6"

[features]
default = []
network = ["dep:reqwest"]
