[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.82"
bytes = "1.6.0"
bzip2 = "0.4.4"
flate2 = "1.0.30"
futures = "0.3.30"
futures-util = "0.3.30"
reqwest = { version = "0.12.4", features = ["blocking", "json", "stream"], optional = true }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
tar = "0.4.40"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread"] }
xz2 = "0.1.7"

[features]
default = []
network = ["dep:reqwest"]
