[package]
name = "blimp-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
common = { path = "../common" }
flate2 = "1.0.30"
tar = "0.4.40"
tokio = "1.37.0"

[features]
default = []
network = ["common/network"]
