name: Check
on: push
jobs:
  format:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - run: cargo +nightly fmt --check
  doc:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - run: cargo +nightly doc
  offline:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Check debug compilation
        run: cargo +nightly build
      - name: Check release compilation
        run: cargo +nightly build --release
      - name: Clippy
        run: cargo +nightly clippy
      - name: Unit tests
        run: cargo +nightly test
  online:
    runs-on: [self-hosted, linux]
    needs: offline
    steps:
      - uses: actions/checkout@v3
      - name: Check debug compilation
        run: cargo +nightly build --features network
      - name: Check release compilation
        run: cargo +nightly build --release --features network
      - name: Clippy
        run: cargo +nightly clippy --features network
      - name: Unit tests
        run: cargo +nightly test --features network
